In [20]:
import torch
import numpy as np
import os

In [21]:
device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cuda'

In [22]:
basic_tensor = torch.tensor([[1,2,3],[11,22,33]])

basic_tensor

tensor([[ 1,  2,  3],
        [11, 22, 33]])

In [4]:
basic_tensor.dtype

torch.int64

In [5]:
basic_tensor.device

device(type='cpu')

In [6]:
basic_tensor.shape

torch.Size([2, 3])

In [9]:
basic_tensor.requires_grad

False

In [10]:
tensor = torch.tensor([[1,2,3],[11,22,33]],
                     dtype=torch.float,
                     device=device,
                     requires_grad=True)

tensor

tensor([[ 1.,  2.,  3.],
        [11., 22., 33.]], device='cuda:0', requires_grad=True)

In [11]:
tensor.dtype

torch.float32

In [12]:
tensor.device

device(type='cuda', index=0)

In [13]:
tensor.requires_grad

True

Other commonly used tensors

In [14]:
x = torch.empty(size=(3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
x = torch.zeros(size=(3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
x=torch.ones(size=(3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
x=torch.rand(size=(3,3))
x

tensor([[0.4048, 0.3929, 0.1519],
        [0.6894, 0.6042, 0.5722],
        [0.5347, 0.4592, 0.7442]])

In [31]:
# identity matrix
x = torch.eye(10)
x

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
x = torch.arange(start=0, end=7, step=2)
x

tensor([0, 2, 4, 6])

In [24]:
x = torch.linspace(start=0, end=7, steps=10)
x

tensor([0.0000, 0.7778, 1.5556, 2.3333, 3.1111, 3.8889, 4.6667, 5.4444, 6.2222,
        7.0000])

In [33]:
x = torch.diag(5*(torch.ones(10)))
x

tensor([[5., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 5., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 5., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 5., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 5., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 5., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 5.]])

In [34]:
x.shape

torch.Size([10, 10])

# conversion

In [35]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [36]:
x.bool()

tensor([False,  True,  True,  True])

In [ ]:
x.int()
tensor([0, 1, 2, 3], dtype=torch.int32)

tensor([0, 1, 2, 3], dtype=torch.int16)

tensor([0, 1, 2, 3])

tensor([0., 1., 2., 3.], dtype=torch.float16)

tensor([0., 1., 2., 3.])

tensor([0., 1., 2., 3.], dtype=torch.float64)



array([[1, 2, 3],
       [1, 2, 3]])

tensor([[1, 2, 3],
        [1, 2, 3]], dtype=torch.int32)


In [45]:
x.short() # int16

tensor([0, 1, 2, 3], dtype=torch.int16)

In [44]:
x.long() # int64

tensor([0, 1, 2, 3])

In [43]:
x.half() # float16

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [42]:
x.float() # float32

tensor([0., 1., 2., 3.])

In [41]:
x.double() # float64

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [37]:
np_array = np.array([[1,2,3], [1,2,3]])
np_array

array([[1, 2, 3],
       [1, 2, 3]])

In [39]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[1, 2, 3],
        [1, 2, 3]], dtype=torch.int32)

In [40]:
tensor.numpy()

array([[1, 2, 3],
       [1, 2, 3]])