# MATHEMATICAL OPERATIONS

In [1]:
import numpy as np
import torch
import os

In [2]:
x = torch.arange(start=10, end=20, step=4)
y = torch.arange(start=5, end=15, step=4)

x.shape, y.shape

(torch.Size([3]), torch.Size([3]))

In [3]:
x

tensor([10, 14, 18])

In [4]:
y

tensor([ 5,  9, 13])

In [5]:
x+y

tensor([15, 23, 31])

In [6]:
x-y

tensor([5, 5, 5])

In [7]:
x*y #element wise multiplication 

tensor([ 50, 126, 234])

In [8]:
torch.dot(x,y)

tensor(410)

In [9]:
sum([ 50, 126, 234])

410

In [10]:
x / y #<< Element wise division

tensor([2.0000, 1.5556, 1.3846])

In [11]:
z = torch.ones(3)
z

tensor([1., 1., 1.])

In [12]:
z=z+x
z

tensor([11., 15., 19.])

In [13]:
## inplace addition
z.add_(x)
z

tensor([21., 29., 37.])

In [14]:
x.pow(2)

tensor([100, 196, 324])

In [15]:
x**2

tensor([100, 196, 324])

In [16]:
# Matrix multpltplication

A = torch.rand(size=(3,5))
B = torch.rand(size=(5,4))

A @ B 

tensor([[0.3781, 0.2789, 0.3400, 0.3656],
        [1.4339, 1.7029, 1.2859, 1.8910],
        [1.2770, 1.2695, 1.2233, 1.3925]])

In [17]:
A.matmul(B)

tensor([[0.3781, 0.2789, 0.3400, 0.3656],
        [1.4339, 1.7029, 1.2859, 1.8910],
        [1.2770, 1.2695, 1.2233, 1.3925]])

In [18]:
X = torch.rand((3,3))
x

tensor([10, 14, 18])

In [19]:
X.matrix_exp()

tensor([[3.6476, 1.1162, 2.4770],
        [1.6912, 3.0919, 1.3323],
        [1.9405, 1.2681, 2.8488]])

In [20]:
X.matrix_power(2)

tensor([[1.6413, 0.7835, 1.5595],
        [1.1231, 1.2054, 0.9168],
        [1.2505, 0.8190, 1.1467]])

In [21]:
# Broadcasting

A

tensor([[0.0851, 0.0583, 0.0699, 0.3035, 0.2009],
        [0.8578, 0.9588, 0.5676, 0.1853, 0.3768],
        [0.4908, 0.9285, 0.3715, 0.7291, 0.0905]])

In [22]:
A + 1

tensor([[1.0851, 1.0583, 1.0699, 1.3035, 1.2009],
        [1.8578, 1.9588, 1.5676, 1.1853, 1.3768],
        [1.4908, 1.9285, 1.3715, 1.7291, 1.0905]])

In [23]:
A-1

tensor([[-0.9149, -0.9417, -0.9301, -0.6965, -0.7991],
        [-0.1422, -0.0412, -0.4324, -0.8147, -0.6232],
        [-0.5092, -0.0715, -0.6285, -0.2709, -0.9095]])

In [24]:
A * 5

tensor([[0.4256, 0.2913, 0.3495, 1.5173, 1.0046],
        [4.2891, 4.7942, 2.8378, 0.9264, 1.8840],
        [2.4539, 4.6423, 1.8573, 3.6454, 0.4523]])

In [25]:
A.shape

torch.Size([3, 5])

In [26]:
C = torch.ones((1,5))
C

tensor([[1., 1., 1., 1., 1.]])

In [27]:
A - C

tensor([[-0.9149, -0.9417, -0.9301, -0.6965, -0.7991],
        [-0.1422, -0.0412, -0.4324, -0.8147, -0.6232],
        [-0.5092, -0.0715, -0.6285, -0.2709, -0.9095]])

In [28]:
A+C

tensor([[1.0851, 1.0583, 1.0699, 1.3035, 1.2009],
        [1.8578, 1.9588, 1.5676, 1.1853, 1.3768],
        [1.4908, 1.9285, 1.3715, 1.7291, 1.0905]])

In [29]:
D = torch.ones((3, 1))
D

tensor([[1.],
        [1.],
        [1.]])

In [30]:
A+D

tensor([[1.0851, 1.0583, 1.0699, 1.3035, 1.2009],
        [1.8578, 1.9588, 1.5676, 1.1853, 1.3768],
        [1.4908, 1.9285, 1.3715, 1.7291, 1.0905]])

In [31]:
A-D

tensor([[-0.9149, -0.9417, -0.9301, -0.6965, -0.7991],
        [-0.1422, -0.0412, -0.4324, -0.8147, -0.6232],
        [-0.5092, -0.0715, -0.6285, -0.2709, -0.9095]])

In [32]:
torch.sum(D)

tensor(3.)

In [33]:
torch.max(A)

tensor(0.9588)

In [34]:
torch.min(A)

tensor(0.0583)

In [35]:
torch.argmax(A)

tensor(6)

In [36]:
torch.argmin(A)

tensor(1)

In [37]:
torch.min(A, dim=1)#row wise

torch.return_types.min(
values=tensor([0.0583, 0.1853, 0.0905]),
indices=tensor([1, 3, 4]))

In [38]:
torch.max(A, dim=1)

torch.return_types.max(
values=tensor([0.3035, 0.9588, 0.9285]),
indices=tensor([3, 1, 1]))

In [39]:
torch.min(A, dim=0)#col wise

torch.return_types.min(
values=tensor([0.0851, 0.0583, 0.0699, 0.1853, 0.0905]),
indices=tensor([0, 0, 0, 1, 2]))

In [40]:
A=0-A
A

tensor([[-0.0851, -0.0583, -0.0699, -0.3035, -0.2009],
        [-0.8578, -0.9588, -0.5676, -0.1853, -0.3768],
        [-0.4908, -0.9285, -0.3715, -0.7291, -0.0905]])

In [42]:
torch.abs(A)

tensor([[0.0851, 0.0583, 0.0699, 0.3035, 0.2009],
        [0.8578, 0.9588, 0.5676, 0.1853, 0.3768],
        [0.4908, 0.9285, 0.3715, 0.7291, 0.0905]])

In [43]:
torch.argmax(A, dim=1) # row wise argmax

tensor([1, 3, 4])

In [44]:
torch.argmax(A, dim=0) # col wise argmax

tensor([0, 0, 0, 1, 2])

In [45]:
torch.mean(A)

tensor(-0.4183)

In [46]:
torch.mean(A, dim=1) # row wise mean

tensor([-0.1435, -0.5893, -0.5220])

In [47]:
torch.mean(A, dim=0) # col wise mean

tensor([-0.4779, -0.6485, -0.3363, -0.4059, -0.2227])

In [48]:
A

tensor([[-0.0851, -0.0583, -0.0699, -0.3035, -0.2009],
        [-0.8578, -0.9588, -0.5676, -0.1853, -0.3768],
        [-0.4908, -0.9285, -0.3715, -0.7291, -0.0905]])

In [49]:
D = torch.ones(A.shape)
D

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [50]:
torch.eq(A, D)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [51]:
torch.eq(D, D)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [52]:
torch.sort(A)

torch.return_types.sort(
values=tensor([[-0.3035, -0.2009, -0.0851, -0.0699, -0.0583],
        [-0.9588, -0.8578, -0.5676, -0.3768, -0.1853],
        [-0.9285, -0.7291, -0.4908, -0.3715, -0.0905]]),
indices=tensor([[3, 4, 0, 2, 1],
        [1, 0, 2, 4, 3],
        [1, 3, 0, 2, 4]]))

In [53]:
torch.clamp(A, min=0.5)

tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]])